service: serverless-graphql

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: provided.al2
  stage: dev
  region: eu-central-1

package:
  exclude:
    - .deno_dir/gen/file
    - node_modules
    - .vscode
    - package-lock.json

functions:
  graphql:
    handler: index.Echo
    layers:
      - arn:aws:lambda:eu-central-1:536277455697:layer:deno:3
    memorySize: 128
    events:
      - http:
          path: graphql
          method: ANY
          cors: true

resources:
  Transform: AWS::Serverless-2016-10-31
  Resources:
    Deno:
      Type: AWS::Serverless::Application
      Properties:
        Location:
          ApplicationId: arn:aws:serverlessrepo:us-east-1:390065572566:applications/deno
          SemanticVersion: 1.29.2

plugins:
  - serverless-scriptable-plugin